---
- hosts: webservers
  vars:
    globomantics_site_path: "c:\\inetpub\\wwwroot\\globosite"
    default_index_file_01: "index-01.html"
    default_index_file_02: "index-02.html"
  tasks:
    - name: Ensure that IIS is installed
      win_feature:
        name: "Web-Server"
        state: present
        restart: no
        include_sub_features: no
        include_management_tools: no

    - name: Ensure the globomantics website directory is created
      win_file:
        path: "{{ globomantics_site_path }}"
        state: directory

    - name: Create sub iis website
      win_iis_website:
        name: "Globomantics Application"
        state: started
        port: 8080
        physical_path: "{{ globomantics_site_path }}"

    - name: Copy default index file to site for globo-web01
      win_copy:
        src: "{{ default_index_file_01 }}"
        dest: "{{ globomantics_site_path}}\\index.html"
      when: ansible_facts['hostname'] == "globo-web01"

    - name: Copy default index file to site for globo-web02
      win_copy:
        src: "{{ default_index_file_02 }}"
        dest: "{{ globomantics_site_path}}\\index.html"
      when: ansible_facts['hostname'] == "globo-web02"        

    - name: Ensure filewall rule is in place for site
      win_firewall_rule:
        name: Globomantics
        enabled: yes
        state: present
        localport: 8080
        action: allow
        direction: in
        protocol: tcp
      
    
